### ISSUE TITLE
Event not persisted in onChange method.

### ISSUE THREAD

**Issue by prabhath** [ianmcnally/react-currency-masked-input#12]
I have a onChange method in my class which uses currency-masked-input

```
handleChange(event, maskedValue) {
//Code
}
```

The event I got has null values and there are warnings in the console like this.

> index.js:1182 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by ianmcnally** [comment]
Visit the link React's (really great) error for more information on why that's happening. It's by design. This is not a problem with this library.

**Comment by prabhath** [comment]
```
{
    key: 'onChange',
    value: function onChange(evt) {
      var _this = this;

      var value = this._maskedInputValue(evt.target.value, evt.target.validity);
evet.persist();   //This should be there when passing the event to callback
      this.setState({ value: value }, function () {
        if (_this.props.onChange) {
          // call original callback, if it exists
          _this.props.onChange(evt, value);
        }
      });
    }
  }
```

See the commented evet.persist(); This was not in your library code. I think it should be there. I am new to React. Please correct me if I am wrong.

**Comment by ianmcnally** [comment]
Adding event persistance in 2.0. Thanks for the getting my attention on this; should have done it sooner!

**Comment by ianmcnally** [comment]
Done in 2.0!
