### ISSUE TITLE
value & defaultProps console warning even with default example input

### ISSUE THREAD

**Issue by rublev** [ianmcnally/react-currency-masked-input#14]
Not much to say except that the following does not yield errors:

`<CurrencyInput name="myInput" required />`

but the following leads to the error below it:

`<CurrencyInput name="myInput" required defaultValue="0" />`

`CurrencyInput contains an input of type number with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props.`

The code I have this in is within a bare component and the render looks like so:

	return (
		<div className='buy-bitcoin'>
			<CurrencyInput name="myInput" required defaultValue="0" />
		</div>
	)

**Comment by ianmcnally** [comment]
Thanks for reporting, rublev. I need some more information to start debugging. Can you send the your versions of this lib and React?

**Comment by rublev** [comment]
Ah yes my bad:

```
"react": "^15.4.2",
"react-dom": "^15.3.1",
"react-currency-masked-input": "^2.0.1",
```

**Comment by ianmcnally** [comment]
Found the fix, and realized my test case wasn't showing an error! Rendering into the DOM, instead of shallow rendering did the trick.

For the bug you reported, I needed to blacklist props.defaultValue. 

Hope this fixes your issue, and thanks again for reporting it!

**Comment by rublev** [comment]
No problem, thanks for fixing it so quickly.
