### ISSUE TITLE
How do you add commas?

### ISSUE THREAD

**Issue by rublev** [ianmcnally/react-currency-masked-input#15]

**Comment by ianmcnally** [comment]
It's not possible yet. A pull request would be most welcome. Otherwise, I can put it on the backlog.

**Comment by rublev** [comment]
@ianmcnally patrickkee committed some code that looks like added commas, what's wrong with this? https://github.com/ianmcnally/react-currency-masked-input/pull/7

**Comment by ianmcnally** [comment]
#7 was never finished (failing tests), so I never reviewed it.

**Comment by ianmcnally** [comment]
This was added in #41
