### ISSUE TITLE
"Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

### ISSUE THREAD

**Issue by rublev** [ianmcnally/react-currency-masked-input#16]
Looks like this library needs a small update! I currently get this error in console.

**Comment by ianmcnally** [comment]
Thanks rublev! I'll make sure it gets some TLC soon.

**Comment by ianmcnally** [comment]
Closed in commit 6c6d0a33a1c68ccf14e5ed9e6df9dfdc40dd20c8 and published in version 2.1.0.
