### ISSUE TITLE
Why value from input it's different from 'maskedvalue'?

### ISSUE THREAD

**Issue by RodolfoQMartins** [ianmcnally/react-currency-masked-input#38]
Example, when input it was "23.33":

`handleChangePrice = (maskedvalue: number) => {
        console.warn(maskedvalue);
    }`

This function above returns 23.33 witch its perfect! But this one:

`handleChangePrice = (e) => {
        console.warn(e.target.value);
    }`

Returns "2.333". By the way i'm using TypeScript.

**Comment by ianmcnally** [comment]
The second argument to handlePriceChange is the masked value, so that should get you the value you want. The reason you're seeing the event.target.value as different is because it hasn't been masked yet. 

Closing this, but let me know if you have any more question.
