### ISSUE TITLE
Trying to clear the input not working, easy fix

### ISSUE THREAD

**Issue by IvoFritsch** [ianmcnally/react-currency-masked-input#44]
I'm using this as an controlled Input, all is working fine, but when i try to clear the input, setting an empty string, the component ignores it and keeps showing the old value

this can easily be fixed by replacing the line 35 of the `/src/components/currency-input.js` file, that currently is:
`return this.props.value || this.state.value`
by
`return this.props.value !== undefined ? this.props.value : this.state.value`

Thanks in advance for the nice and easy to use component

**Comment by ianmcnally** [comment]
Hey @IvoFritsch, thanks for submitting an issue. Just so I can diagnose this right, you've got an input that's been updating, but want to clear it out by passing an empty '' as the value at some point after a state update?

**Comment by IvoFritsch** [comment]
@ianmcnally Yes, its exactly this tha I was trying

**Comment by ianmcnally** [comment]
Fixed and released in v2.4.0. Thanks for the submission, @IvoFritsch!
