### ISSUE TITLE
Controlled vs Uncontrolled Input

### ISSUE THREAD

**Issue by Jador** [ianmcnally/react-currency-masked-input#8]
First off, this component has been a real lifesaver (I secretly hate implementing masked inputs lol). I do have one suggestion.

Looking at the readme:

> Will use the value prop passed in as an initial value, but will take over from there.

Makes it sound like the component behaves as an [uncontrolled component](https://facebook.github.io/react/docs/forms.html#uncontrolled-components).

> Can manually update value by triggering a re-render of the component.

But this behaviour effectively makes it a [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components).

This caused a moment of confusion on my team today, especially as the former was the desired behaviour.

I think it could be useful to support both using the same semantics react does; i.e. `value` keeps the component in sync with the props, `defaultValue` sets it the one time and goes.

What do you think? I can probably whip up a PR pretty quick if you agree.

**Comment by ianmcnally** [comment]
That's a fantastic idea! A PR would be greatly appreciated.

**Comment by ianmcnally** [comment]
Done in 2.0!
